---
title: "2017 CDI Conference"
date: "2017-05-19"
slug: "introR-CDI-May17"
output: USGSmarkdowntemplates::hugoTraining_course
parent: Course Specific Material
---

May 19, 2017 in Denver, CO

### Installation
See [Before the Workshop](/intro-curriculum/Before) for information on what software should be installed prior to the course.

### Data files
Please download `course_NWISdata.csv` and `course_NWISdata_cleaned.csv` datasets from the [Data page](/intro-curriculum/data/) <span style="color:red">prior to the start of the course</span>. 

### Tentative schedule

* 08:00 am -- Instructors available for questions/setup assistance
* 08:30 am -- [Introduction](/intro-curriculum/Introduction) (navigate RStudio + fxns/pkgs + finding help)
* 09:30 am -- [Get](/intro-curriculum/Get) (data types + data structures + read in CSVs)
* 10:15 am -- *Break*
* 10:30 am -- [Clean](/intro-curriculum/Clean) (subset data, get rid of bad values) 
* 11:30 am -- *Lunch*
* 12:30 pm -- [Explore](/intro-curriculum/Explore) (basic statistics)
* 01:15 pm -- Plot data
* 02:15 pm -- *Break*
* 02:30 pm -- Using the [dataRetrieval](https://owi.usgs.gov/R/dataRetrieval.html) package
* 03:30 pm -- [Repeat](/intro-curriculum/Reproduce/) (reproducibility + if-else/loops + R Markdown)
* 04:15 pm -- Questions/Final thoughts

### Script files

[This zip file](https://drive.google.com/file/d/0B54YFPSk4XN8NlVZcUdzRHJDa0U) contains the project folder and `.Rproj` file with the scripts that the instructors created in the class. Download and unzip to access.

### Additional resources
* [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) (data wrangling, visualization, shiny, markdown, RStudio, etc)
* [USGS-R GitHub](https://github.com/USGS-R) (package source code + bug/feature reporting)
* [USGS-R blog](https://owi.usgs.gov/blog/tags/r)

### Instructors

Lindsay Carr (lcarr@usgs.gov)

Will Farmer (wfarmer@usgs.gov)

Joe Mills (tmills@usgs.gov)
