---
title: "LLNL Intro to R Training"
date: "2019-01-29"
slug: "introR-LLNL-Jan19"
output: USGSmarkdowntemplates::hugoTraining_course
parent: Course Specific Material
---
January 29-31, 2019 at the Lawrence Livermore National Laboratory.

### Installation

See [R Installation Instructions](/installr) for information on what software should be installed prior to the course. 

### Tentative schedule

**Day 1**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 09:30 am -- [Introduction](/intro-curriculum/Introduction)
* 09:30 am - 10:00 am -- [Example workflow](/intro-curriculum/data/data_workflow.Rmd)
* 10:00 am - 10:15 am -- *Break*
* 10:15 am - 12:00 pm -- [Get](/intro-curriculum/Get)
* 12:00 am - 01:00 pm -- *Lunch*
* 01:00 pm - 03:00 pm -- [Clean](/intro-curriculum/Clean)
* 03:00 pm - 03:15 pm -- *Break*
* 03:15 pm - 04:00 pm -- More [Clean](/intro-curriculum/Clean)
* 04:00 pm - 04:30 pm -- Project time!

**Day 2**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 10:15 am -- [Explore](/intro-curriculum/Explore)
* 10:15 am - 10:30 am -- *Break*
* 10:30 am - 12:00 pm -- [Analyze: Base](/intro-curriculum/Analyze)
* 12:00 pm - 01:00 pm -- *Lunch*
* 01:00 pm - 02:30 pm -- [Analyze: dataRetrieval](https://cran.r-project.org/web/packages/dataRetrieval/dataRetrieval.pdf) 
* 02:30 pm - 02:45 pm -- *Break*
* 02:45 pm - 04:00 pm -- Visualize with ggplot2: [Visualize](/intro-curriculum/ggplot2/)
* 04:00 pm - 04:30 pm -- Project time!

**Day 3**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 10:00 am -- [Repeat](/intro-curriculum/Reproduce/)
* 10:00 am - 12:30 pm -- Project time: [USGS R packages](/intro-curriculum/USGS/), projects (group/individual), or [additional topics](/intro-curriculum/Additional/)

### Data files

Download data from the [Data page](/intro-curriculum/data/).

### Additional resources

* [USGS-R blog](https://owi.usgs.gov/blog/tags/r)
* [USGS-R twitter](https://twitter.com/USGS_R)
* [USGS-R GitHub](https://github.com/USGS-R) (package source code + bug/feature reporting)
* [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) (visualization, shiny, markdown, RStudio, etc)
* [RStudio data wrangling cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
* [R Markdown](http://rmarkdown.rstudio.com/lesson-1.html)
* [dataRetrieval package tutorial](https://owi.usgs.gov/R/dataRetrieval.html#1)

### Instructors

Lindsay Carr Platt (lcarr@usgs.gov)

Kyle Samperton (samperton1@llnl.gov)

### Lesson scripts

After the first day of class, there will be a link to the folder that contains all of instructor's scripts created during the class for your reference.
