---
title: "LMGWSC - Arkansas"
date: "2016-10-25"
slug: "introR-LMGWSCAR-Oct16"
output: USGSmarkdowntemplates::hugo
---

October 25th - 27th in Little Rock, AR

### Installation
See [Before the Workshop](/intro-curriculum/Before) for information on what software should be installed prior to the course.

### Tentative schedule

**Day 1**

* 08:00 am - 09:00 am -- Instructors available for questions 
* 09:00 am - 10:30 am -- [Introduction](/intro-curriculum/Introduction) 
* 10:30 am - 10:45 am -- *Break*
* 10:45 am - 12:00 pm -- [Get](/intro-curriculum/Get)
* 12:00 pm - 01:00 pm -- *Lunch*
* 01:15 pm - 03:15 pm -- [Clean](/intro-curriculum/Clean)
* 03:15 pm - 03:30 pm -- *Break*
* 03:30 pm - 04:30 pm -- [Clean](/intro-curriculum/Clean) continued
* 04:30 pm - 05:00 pm -- End of day wrap-up

**Day 2**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 09:30 am -- [Explore](/intro-curriculum/Explore)
* 09:30 am - 10:30 am -- [Analyze: Base](/intro-curriculum/Analyze)
* 10:30 am - 10:45 am -- *Break*
* 10:45 am - 12:00 pm -- Analyze: [EGRET](https://cran.r-project.org/web/packages/EGRET/EGRET.pdf), [dataRetrieval](https://cran.r-project.org/web/packages/dataRetrieval/dataRetrieval.pdf)
* 12:00 pm - 01:00 pm -- *Lunch*
* 01:00 pm - 02:30 pm -- Visualize: [ggplot2](/intro-curriculum/ggplot2/)
* 02:30 pm - 02:45 pm -- *Break*
* 02:45 pm - 04:00 pm -- Visualize: [ggplot2](/intro-curriculum/ggplot2/) continued
* 04:00 pm - 04:30 pm -- End of day wrap-up

**Day 3**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 10:00 am -- [Repeat](/intro-curriculum/Reproduce/)
* 10:00 am - 10:30 am -- The importance of reproducibility
* 10:30 am - 12:30 pm -- Practice: [USGS R packages](/intro-curriculum/USGS/), projects (group/individual), or [additional topics](/intro-curriculum/Additional/)

### Data files
Download data from the [Data page](/intro-curriculum/data/). 

### Additional resources
* [USGS-R blog](https://owi.usgs.gov/blog/tags/r)
* [USGS-R twitter](https://twitter.com/USGS_R)
* [USGS-R GitHub](https://github.com/USGS-R) (package source code + bug/feature reporting)
* [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) (data wrangling, visualization, shiny, markdown, RStudio, etc)

### Instructors
Emily Read (eread@usgs.gov) -- *primary contact*

Brian Breaker (bbreaker@usgs.gov)

Lucas Driver (ldriver@usgs.gov)

### Lesson scripts

Instructors will be live coding during this course. Our code will be shared with you here at the end.
