---
title: "Columbia River Research Lab"
date: "2016-11-01"
slug: "introR-CRRL-Nov16"
output: USGSmarkdowntemplates::hugoTraining_course
parent: Course Specific Material
---

November 1st - 3rd in Cook, WA

### Installation
See [Before the Workshop](/intro-curriculum/Before) for information on what software should be installed prior to the course.

### Tentative schedule

**Day 1**

* 08:00 am - 08:30 am -- Instructors available for questions 
* 08:30 am - 10:00 am -- [Introduction](/intro-curriculum/Introduction) 
* 10:00 am - 10:15 am -- *Break*
* 10:15 am - 12:00 pm -- [Get](/intro-curriculum/Get)
* 12:00 pm - 01:00 pm -- *Lunch*
* 01:00 pm - 03:00 pm -- [Clean](/intro-curriculum/Clean)
* 03:00 pm - 03:15 pm -- *Break*
* 03:15 pm - 04:15 pm -- [Clean](/intro-curriculum/Clean) continued
* 04:15 pm - 04:30 pm -- End of day wrap-up

**Day 2**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 09:30 am -- [Explore](/intro-curriculum/Explore)
* 09:30 am - 10:30 am -- [Analyze: Base](/intro-curriculum/Analyze)
* 10:30 am - 10:45 am -- *Break*
* 10:45 am - 12:00 pm -- Analyze w/ packages: TBD
* 12:00 pm - 01:00 pm -- *Lunch*
* 01:00 pm - 02:30 pm -- [Visualize: Base](/intro-curriculum/Visualize/)
* 02:30 pm - 02:45 pm -- *Break*
* 02:45 pm - 04:00 pm -- [Visualize: Base](/intro-curriculum/Visualize/) continued
* 04:00 pm - 04:30 pm -- End of day wrap-up

**Day 3**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 10:00 am -- [Repeat](/intro-curriculum/Reproduce/)
* 10:00 am - 10:30 am -- [The importance of reproducibility](https://owi.usgs.gov/blog/Reproducibility)
* 10:30 am - 12:30 pm -- Practice: [USGS R packages](/intro-curriculum/USGS/), projects (group/individual), or [additional topics](/intro-curriculum/Additional/)

### Data files
Download data from the [Data page](/intro-curriculum/data/). 

### Additional resources
* [USGS-R blog](https://owi.usgs.gov/blog/tags/r)
* [USGS-R twitter](https://twitter.com/USGS_R)
* [USGS-R GitHub](https://github.com/USGS-R) (package source code + bug/feature reporting)
* [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) (data wrangling, visualization, shiny, markdown, RStudio, etc)

### Instructors
Jordan Read (jread@usgs.gov)

Jordan Walker (jiwalker@usgs.gov)

David Watkins (wwatkins@usgs.gov)

### Lesson scripts

Instructors will be live coding during this course. Our code will be shared with you here at the end.
