---
title: "New Mexico Water Science Center"
date: "2017-03-14"
slug: "introR-NMWSC-Mar14"
output: USGSmarkdowntemplates::hugoTraining_course
parent: Course Specific Material
---
March 14th - 16th in Albuquerque, NM

### Installation

See [Before the Workshop](/intro-curriculum/Before) for information on what software should be installed prior to the course.

### Tentative schedule

**Day 1**

* 11:30 am - 12:00 pm -- Instructors available for questions
* 12:00 pm - 01:30 pm -- [Introduction](/intro-curriculum/Introduction)
* 01:30 pm - 02:45 pm -- [Get](/intro-curriculum/Get)
* 02:45 pm - 03:00 pm -- *Break*
* 03:00 pm - 05:00 pm -- [Clean](/intro-curriculum/Clean)

**Day 2**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 09:30 am -- More [Clean](/intro-curriculum/Clean)
* 09:30 am - 11:00 am -- [Explore](/intro-curriculum/Explore)
* 11:00 am - 11:15 am -- *Break*
* 11:15 am - 12:30 pm -- [Analyze: Base](/intro-curriculum/Analyze)
* 12:30 pm - 01:30 pm -- *Lunch*
* 01:30 pm - 03:00 pm -- Visualize with base R: [Visualize](/intro-curriculum/Visualize/)
* 03:00 pm - 03:15 pm -- *Break*
* 03:15 pm - 04:30 pm -- Analyze: USGS packages/TBD

**Day 3**

* 08:00 am - 08:30 am -- Instructors available for questions
* 08:30 am - 11:00 am -- [Repeat](/intro-curriculum/Reproduce/)
* 11:00 am - 03:30 pm -- Leftovers/Practice: [USGS R packages](/intro-curriculum/USGS/), projects (group/individual), or [additional topics](/intro-curriculum/Additional/)

### Data files

Download data from the [Data page](/intro-curriculum/data/).

### Additional resources

* [USGS-R blog](https://owi.usgs.gov/blog/tags/r)
* [USGS-R twitter](https://twitter.com/USGS_R)
* [USGS-R GitHub](https://github.com/USGS-R) (package source code + bug/feature reporting)
* [RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) (visualization, shiny, markdown, RStudio, etc)
* [RStudio data wrangling cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
* [R Markdown](http://rmarkdown.rstudio.com/lesson-1.html)
* [dataRetrieval package tutorial](https://owi.usgs.gov/R/dataRetrieval.html#1)

### Instructors

Lindsay Carr (lcarr@usgs.gov) -- *primary contact*

David Watkins (wwatkins@usgs.gov)

Jordan Walker (jiwalker@usgs.gov)

Alicia Rhoades (arhoades@usgs.gov)

### Lesson scripts

[This zip file](https://drive.google.com/file/d/0B54YFPSk4XN8MXFieVBIOXljanc) contains the project folder and `.Rproj` file with the scripts that the instructors created in the class.
